services:
  app:
    build:
      context: .
      args:
        PRISMA_ENGINES_MIRROR: ${PRISMA_ENGINES_MIRROR:-https://registry.npmmirror.com/-/binary/prisma}
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      CRON_SECRET: ${CRON_SECRET}
      PUSH_CHANNELS: ${PUSH_CHANNELS:-}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-}
      FEISHU_WEBHOOK_URL: ${FEISHU_WEBHOOK_URL:-}
      FEISHU_SIGN_SECRET: ${FEISHU_SIGN_SECRET:-}
      PRISMA_ENGINES_MIRROR: ${PRISMA_ENGINES_MIRROR:-https://registry.npmmirror.com/-/binary/prisma}
